fixed sudo usage (use subshells where appropriate)

diff --git a/bin/mn_disable_swap b/bin/mn_disable_swap
--- a/bin/mn_disable_swap
+++ b/bin/mn_disable_swap
@@ -6,9 +6,9 @@ BASEDIR=`dirname $0`/..
 echo "Disabling swap:"
 if [[ -n `which dphys-swapfile 2> /dev/null` ]] ; then
 	echo -n "Trying dphys-swapfile... "
-	sudo dphys-swapfile swapoff && dphys-swapfile uninstall && success || failure
+	sudo dphys-swapfile swapoff && sudo dphys-swapfile uninstall && success || failure
 else
 	echo -n "Trying manual method... "
-	sudo swapoff -a && sed -i '/^[^#]/ s/\(^.*swap.*$\)/#\ \1/' /etc/fstab && success || failure
+	sudo swapoff -a && sudo sed -i '/^[^#]/ s/\(^.*swap.*$\)/#\ \1/' /etc/fstab && success || failure
 fi
 
diff --git a/bin/mn_set_hostname b/bin/mn_set_hostname
--- a/bin/mn_set_hostname
+++ b/bin/mn_set_hostname
@@ -1,9 +1,13 @@
 #!/bin/bash
+BASEDIR=`dirname $0`/..
+. "$BASEDIR"/bin/mn_includes
+
 
 # This helper creates a unique host name based on the non-vendor part of the ethernet MAC address.
 MAC_LOCALPART=`ip link show |  awk '$1 ~ /ether/ { print $2 }' | sed 's/\://g' | head -n 1 | cut -c 7-12`
 NEW_HOSTNAME="mn_$MAC_LOCALPART"
 echo -n "Setting hostname to $NEW_HOSTNAME..."
-sudo echo "$NEW_HOSTNAME" > /etc/hostname && echo " succeeded." || echo " failed."
+sudo /bin/bash -c 'echo "$NEW_HOSTNAME" > /etc/hostname' && success || failure
 echo -n "Modifying hosts file..."
-sudo sed -i "s/$HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts && echo " succeeded." || echo " failed."
+sudo sed -i "s/$HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts && success || failure
+
