use sudo throughout to save typing during system bootstrap process

diff --git a/bin/mn_generate_locales b/bin/mn_generate_locales
--- a/bin/mn_generate_locales
+++ b/bin/mn_generate_locales
@@ -7,21 +7,21 @@ TIMEZONE="Europe/Berlin"
 DEFAULTLOCALE="en_US.UTF-8"
 OTHERLOCALES="en_GB.UTF-8 de_DE.UTF-8"
 
-echo "Activating locales"
+echo "Activating locales..."
 for i in $DEFAULTLOCALE $OTHERLOCALES ; do
 	echo -ne "\t$i"
-	sed -i "s/\#.*$i/$i/" /etc/locale.gen && success || failure
+	sudo sed -i "s/\#.*$i/$i/" /etc/locale.gen && success || failure
 done
 
 echo "Setting default locale to \'$DEFAULTLOCALE\'... "
-echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
-	dpkg-reconfigure --frontend=noninteractive locales && \
-	update-locale LANG=en_US.UTF-8 \
+sudo echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
+	sudo dpkg-reconfigure --frontend=noninteractive locales && \
+	sudo update-locale LANG=en_US.UTF-8 \
 	&& success || bail
 
 echo -n "Setting timezone to $TIMEZONE... "
-echo "$TIMEZONE" > /etc/timezone \
-	&& dpkg-reconfigure -f noninteractive tzdata \
+sudo echo "$TIMEZONE" > /etc/timezone \
+	&& sudo dpkg-reconfigure -f noninteractive tzdata \
 	&& success || bail
 
 
diff --git a/bin/mn_set_hostname b/bin/mn_set_hostname
--- a/bin/mn_set_hostname
+++ b/bin/mn_set_hostname
@@ -4,6 +4,6 @@
 MAC_LOCALPART=`ip link show |  awk '$1 ~ /ether/ { print $2 }' | sed 's/\://g' | head -n 1 | cut -c 7-12`
 NEW_HOSTNAME="mn_$MAC_LOCALPART"
 echo -n "Setting hostname to $NEW_HOSTNAME..."
-echo "$NEW_HOSTNAME" > /etc/hostname && echo " succeeded." || echo " failed."
+sudo echo "$NEW_HOSTNAME" > /etc/hostname && echo " succeeded." || echo " failed."
 echo -n "Modifying hosts file..."
-sed -i "s/$HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts && echo " succeeded." || echo " failed."
+sudo sed -i "s/$HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts && echo " succeeded." || echo " failed."
