fix broken locales generation (wrong quotes for shell expansion)

diff --git a/bin/mn_generate_locales b/bin/mn_generate_locales
--- a/bin/mn_generate_locales
+++ b/bin/mn_generate_locales
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+BASEDIR=`dirname $0`
+. "$BASEDIR"/mn_includes
+
+
 TIMEZONE="Europe/Berlin"
 DEFAULTLOCALE="en_US.UTF-8"
 OTHERLOCALES="en_GB.UTF-8 de_DE.UTF-8"
@@ -7,19 +11,17 @@ OTHERLOCALES="en_GB.UTF-8 de_DE.UTF-8"
 echo -n "Setting timezone to \'$TIMEZONE\'... "
 echo "$TIMEZONE" > /etc/timezone \
 	&& dpkg-reconfigure -f noninteractive tzdata \
-	&& echo "succeeded." \
-	|| echo "failed."
-echo -n "Activating locales"
+	&& success || bail
+echo "Activating locales"
+
 for i in $DEFAULTLOCALE $OTHERLOCALES ; do
-	echo -n " $i"
-	sed -i -e 's/# $i/$i/' /etc/locale.gen
+	echo -ne "\t$i"
+	sed -i "s/\#.*$i/$i/" /etc/locale.gen && success || failure
 done
-echo "."
 
 echo "Setting default locale to \'$DEFAULTLOCALE\'... "
 echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
 	dpkg-reconfigure --frontend=noninteractive locales && \
 	update-locale LANG=en_US.UTF-8 \
-	&& echo "succeded." \
-	|| echo "failed."
+	&& success || bail
 
