allow optional text message for standard success/failure/bail

diff --git a/bin/mn_includes b/bin/mn_includes
--- a/bin/mn_includes
+++ b/bin/mn_includes
@@ -20,14 +20,14 @@ function success {
 
 function failure {
 
-  echo  -e " \033[1;31mfailed with return code $?.\033[0m"
+  echo  -e " \033[1;31mfailed with return code $?. $@\033[0m"
 
 }
 
 
 function bail {
 
-  failure
+  failure $@
   echo -e "\033[1;31mExiting.\033[0m"
 
   exit 1
