use global include

diff --git a/bin/mn_set_machine_id b/bin/mn_set_machine_id
--- a/bin/mn_set_machine_id
+++ b/bin/mn_set_machine_id
@@ -1,10 +1,11 @@
 #!/bin/bash
 
+BASEDIR=`dirname $0`/..
+. "$BASEDIR"/bin/mn_includes
+
 # This helper creates a unique machine ID for DBUS.
 
 MID=`/usr/bin/dbus-uuidgen`
 echo -n "Setting machine ID to new random value \'$MID\'..."
-echo "$MID" > /etc/machine-id \
-	&& echo "succeeded." \
-	|| echo "failed."
+echo "$MID" > /etc/machine-id && success || failure
 
