handle port connections of systemd JACK services with separate script, works around missing newline support in systemd environment (fix not yet in stretch)

diff --git a/overlay/usr/local/bin/mn_config_update b/overlay/usr/local/bin/mn_config_update
--- a/overlay/usr/local/bin/mn_config_update
+++ b/overlay/usr/local/bin/mn_config_update
@@ -120,25 +120,26 @@ while read UNIT ; do
 	CONFIG="Environment=\"OPTIONS="
 	CONFIG+=`echo $OPTIONS | sed "s/%jackName%/\'$JACKNAME\'/g"`
 	CONFIG+="\""
+	echo "Writing to $DROPIN_DIR/$DROPIN_FILE ..."
+	echo -e "$CONFIG"
+	CONFIG="$NOEDIT\n\n\n[Service]\n\n$CONFIG"
+	echo -e "$CONFIG" > "$DROPIN_DIR"/"$DROPIN_FILE" && success || failure
+
+
 	COUT=`cat "$CONFIG_FILE" | jq --arg unit $UNIT -rjf "$PREFIX"/overlay/usr/local/lib/mn_config/output_connections.jq`
 	if [[ "$COUT" ]] ; then
-		COUT="Environment=\"CONNECTIONS_OUT='$COUT'\""
+		CONFIG="CONNECTIONS_OUT=\"$COUT\n\"\n"
 	fi
 	CIN=`cat "$CONFIG_FILE" | jq --arg unit $UNIT -rjf "$PREFIX"/overlay/usr/local/lib/mn_config/input_connections.jq`
 	if [[ "$CIN" ]] ; then
-		CIN="Environment=\"CONNECTIONS_IN='$CIN'\""
+		CONFIG+="CONNECTIONS_IN=\"$CIN\n\"\n"
 	fi
-	echo "Writing to $DROPIN_DIR/$DROPIN_FILE ..."
+
+	echo "Writing to $DROPIN_DIR/$UNIT.$TYPE.connections ..."
 	echo -e "$CONFIG"
-	echo "$COUT"
-	echo "$CIN"
-	echo -en "\t..."
-	CONFIG="$NOEDIT\n\n\n[Service]\n\n$CONFIG"
-	{
-		echo -e "$CONFIG"
-		echo "$COUT"
-		echo "$CIN"
-	}  > "$DROPIN_DIR"/"$DROPIN_FILE" && success || failure
+	CONFIG="$NOEDIT\n\n$CONFIG"
+	echo -e "$CONFIG" > "$DROPIN_DIR"/"$UNIT"."$TYPE".connections && success || failure
+
 done <<< "$DATA"
 
 
