make mn_config_update less verbose only write unit config files when there is an entry in medianet.json

diff --git a/overlay/usr/local/bin/mn_config_update b/overlay/usr/local/bin/mn_config_update
--- a/overlay/usr/local/bin/mn_config_update
+++ b/overlay/usr/local/bin/mn_config_update
@@ -180,40 +180,44 @@ echo -n "Performing 'systemctl daemon-reload'..."
 $SYSTEMCTL daemon-reload && success || failure
 
 
-scream "Update mod-host configuration:"
-
+# mod-host
 CONFIG=
-DATA=`cat "$CONFIG_FILE" | "$JQ" -r '.systemdUnits[]? | select(.unit == "mod-host") | .config[]'`
-while read COMMAND ; do
-	CONFIG+="$COMMAND\n"
-done <<< "$DATA"
-echo -en "$CONFIG"
-CONFIG="$NOEDIT\n\n$CONFIG"
-echo -n "Writing to $CONF_FILE_MODHOST..."
-echo -e "$CONFIG" > "$CONF_FILE_MODHOST" && success || failure
+DATA=`cat "$CONFIG_FILE" | "$JQ" -r '.systemdUnits[]? | select(.unit == "mod-host") | .config[]?'`
+if [[ -n "$DATA" ]] ; then
+	scream "Update mod-host configuration:"
+	while read COMMAND ; do
+		CONFIG+="$COMMAND\n"
+	done <<< "$DATA"
+	echo -en "$CONFIG"
+	CONFIG="$NOEDIT\n\n$CONFIG"
+	echo -n "Writing to $CONF_FILE_MODHOST..."
+	echo -e "$CONFIG" > "$CONF_FILE_MODHOST" && success || failure
+fi
 
-
-scream "Update shairport-sync configuration:"
-
+# shairport-sync
 CONFIG=
-DATA=`cat "$CONFIG_FILE" | "$JQ" -r '.systemdUnits[]? | select(.unit == "shairport-sync") | .config[]'`
-while read COMMAND ; do
-        CONFIG+="$COMMAND\n"
-done <<< "$DATA"
-echo -en "$CONFIG"
-CONFIG="$NOEDIT\n\n$CONFIG"
-echo -n "Writing to $CONF_FILE_SHAIRPORT_SYNC..."
-echo -e "$CONFIG" > "$CONF_FILE_SHAIRPORT_SYNC" && success || failure
+DATA=`cat "$CONFIG_FILE" | "$JQ" -r '.systemdUnits[]? | select(.unit == "shairport-sync") | .config[]?'`
+if [[ -n "$DATA" ]] ; then
+	scream "Update shairport-sync configuration:"
+	while read COMMAND ; do
+		CONFIG+="$COMMAND\n"
+	done <<< "$DATA"
+	echo -en "$CONFIG"
+	CONFIG="$NOEDIT\n\n$CONFIG"
+	echo -n "Writing to $CONF_FILE_SHAIRPORT_SYNC..."
+	echo -e "$CONFIG" > "$CONF_FILE_SHAIRPORT_SYNC" && success || failure
+fi
 
-
-scream "Update zita-lrx configuration:"
-
+# zita-lrx
 CONFIG=
-DATA=`cat "$CONFIG_FILE" | "$JQ" -r '.systemdUnits[]? | select(.unit == "zita-lrx") | .config[]'`
-while read COMMAND ; do
-	CONFIG+="$COMMAND\n"
-done <<< "$DATA"
-echo -en "$CONFIG"
-CONFIG="$NOEDIT\n\n$CONFIG"
-echo -n "Writing to $CONF_FILE_ZITALRX..."
-echo -e "$CONFIG" > "$CONF_FILE_ZITALRX" && success || failure
+DATA=`cat "$CONFIG_FILE" | "$JQ" -r '.systemdUnits[]? | select(.unit == "zita-lrx") | .config[]?'`
+if [[ -n "$DATA" ]] ; then
+	scream "Update zita-lrx configuration:"
+	while read COMMAND ; do
+		CONFIG+="$COMMAND\n"
+	done <<< "$DATA"
+	echo -en "$CONFIG"
+	CONFIG="$NOEDIT\n\n$CONFIG"
+	echo -n "Writing to $CONF_FILE_ZITALRX..."
+	echo -e "$CONFIG" > "$CONF_FILE_ZITALRX" && success || failure
+fi
