remove dphys-swapfile.service call (does not exist any more in trixie)

diff --git a/sbin/mn_disable_swap b/sbin/mn_disable_swap
--- a/sbin/mn_disable_swap
+++ b/sbin/mn_disable_swap
@@ -12,6 +12,8 @@ else
 	echo -n "Trying manual method... "
 	"$SWAPOFF" -a && "$SED" -i '/^[^#]/ s/\(^.*swap.*$\)/#\ \1/' /etc/fstab && success || failure
 fi
-"$SYSTEMCTL" disable dphys-swapfile && success || failure
+
+# obsolete for trixie:
+# "$SYSTEMCTL" disable dphys-swapfile && success || failure
 
 
